loadstring(game:HttpGet("https://raw.githubusercontent.com/AlexScripts1/Notification/main/Notri", true))()

local VegaXAndroidUI = Instance.new("ScreenGui")
local SettingsWindow = Instance.new("Frame")
local WindowMainTitle = Instance.new("TextLabel")
local CloseB = Instance.new("ImageButton")
local ScrollingFrame = Instance.new("ScrollingFrame")
local UIListLayout = Instance.new("UIListLayout")
local S2 = Instance.new("Frame")
local Title = Instance.new("TextLabel")
local SubTitle = Instance.new("TextLabel")
local UICorner = Instance.new("UICorner")
local SubmitFPS = Instance.new("ImageButton")
local UICorner_2 = Instance.new("UICorner")
local FPSTextBox = Instance.new("TextBox")
local UICorner_3 = Instance.new("UICorner")
local ResetFPS = Instance.new("ImageButton")
local UICorner_4 = Instance.new("UICorner")
local S3 = Instance.new("Frame")
local Title_2 = Instance.new("TextLabel")
local SubTitle_2 = Instance.new("TextLabel")
local UICorner_5 = Instance.new("UICorner")
local SubmitCode = Instance.new("ImageButton")
local UICorner_6 = Instance.new("UICorner")
local InjectCodeTextbox = Instance.new("TextBox")
local UICorner_7 = Instance.new("UICorner")
local ResetCode = Instance.new("ImageButton")
local UICorner_8 = Instance.new("UICorner")
local S1 = Instance.new("Frame")
local Title_3 = Instance.new("TextLabel")
local SubTitle_3 = Instance.new("TextLabel")
local UICorner_9 = Instance.new("UICorner")
local AccentColorPreview = Instance.new("Frame")
local UICorner_10 = Instance.new("UICorner")
local SubmitAccent = Instance.new("ImageButton")
local UICorner_11 = Instance.new("UICorner")
local AccentTextBox = Instance.new("TextBox")
local UICorner_12 = Instance.new("UICorner")
local S4 = Instance.new("Frame")
local Title_4 = Instance.new("TextLabel")
local SubTitle_4 = Instance.new("TextLabel")
local UICorner_13 = Instance.new("UICorner")
local ToggleBTN = Instance.new("TextButton")
local UICorner_14 = Instance.new("UICorner")
local S0 = Instance.new("Frame")
local Title_5 = Instance.new("TextLabel")
local SubTitle_5 = Instance.new("TextLabel")
local UICorner_15 = Instance.new("UICorner")
local UIGradient = Instance.new("UIGradient")
local VegaXLogo = Instance.new("ImageLabel")
local ScriptHubWindow = Instance.new("Frame")
local WindowMainTitle_2 = Instance.new("TextLabel")
local CloseB_2 = Instance.new("ImageButton")
local ScrollingFrame_2 = Instance.new("ScrollingFrame")
local S1_2 = Instance.new("Frame")
local Execute = Instance.new("ImageButton")
local UICorner_16 = Instance.new("UICorner")
local UICorner_17 = Instance.new("UICorner")
local ImageLabel = Instance.new("ImageLabel")
local UICorner_18 = Instance.new("UICorner")
local SubTitle_6 = Instance.new("TextLabel")
local Title_6 = Instance.new("TextLabel")
local UIListLayout_2 = Instance.new("UIListLayout")
local SearchBox = Instance.new("TextBox")
local UICorner_19 = Instance.new("UICorner")
local SearchButton = Instance.new("ImageButton")
local WindowSubTitle = Instance.new("TextLabel")
local PaginationFrame = Instance.new("Frame")
local UICorner_20 = Instance.new("UICorner")
local LeftPage = Instance.new("ImageButton")
local RightPage = Instance.new("ImageButton")
local PageLabel = Instance.new("TextLabel")
local SidebarFrame = Instance.new("Frame")
local Banner = Instance.new("Frame")
local HappyGuy = Instance.new("ImageLabel")
local VegaXLogo_2 = Instance.new("ImageLabel")
local TitleLabel = Instance.new("TextLabel")
local ScrollingFrame_3 = Instance.new("ScrollingFrame")
local UIListLayout_3 = Instance.new("UIListLayout")
local UsernamePlace = Instance.new("Frame")
local Title_7 = Instance.new("TextLabel")
local Icon = Instance.new("Frame")
local UICorner_21 = Instance.new("UICorner")
local ProfileImage = Instance.new("ImageLabel")
local UICorner_22 = Instance.new("UICorner")
local Choice1 = Instance.new("Frame")
local Title_8 = Instance.new("TextLabel")
local C1EB = Instance.new("TextButton")
local UICorner_23 = Instance.new("UICorner")
local Icon_2 = Instance.new("Frame")
local UICorner_24 = Instance.new("UICorner")
local ImageLabel_2 = Instance.new("ImageLabel")
local Choice2 = Instance.new("Frame")
local Title_9 = Instance.new("TextLabel")
local C2EB = Instance.new("TextButton")
local UICorner_25 = Instance.new("UICorner")
local Icon_3 = Instance.new("Frame")
local UICorner_26 = Instance.new("UICorner")
local ImageLabel_3 = Instance.new("ImageLabel")
local Choice3 = Instance.new("Frame")
local Title_10 = Instance.new("TextLabel")
local C3EB = Instance.new("TextButton")
local UICorner_27 = Instance.new("UICorner")
local Icon_4 = Instance.new("Frame")
local UICorner_28 = Instance.new("UICorner")
local ImageLabel_4 = Instance.new("ImageLabel")
local VegaXMenuToggleFrame = Instance.new("Frame")
local UICorner_29 = Instance.new("UICorner")
local VegaXMenuToggle = Instance.new("TextButton")
local UICorner_30 = Instance.new("UICorner")
local ImageLabel_5 = Instance.new("ImageLabel")
local DragTouch = Instance.new("ImageLabel")
local KeySystem = Instance.new("Frame")
local MainTitle = Instance.new("TextLabel")
local CloseB_3 = Instance.new("ImageButton")
local TextBox = Instance.new("TextBox")
local UICorner_31 = Instance.new("UICorner")
local ApproveKeyB = Instance.new("TextButton")
local UICorner_32 = Instance.new("UICorner")
local EULALabel = Instance.new("TextLabel")
local GetKeyB = Instance.new("TextButton")
local UICorner_33 = Instance.new("UICorner")
local JoinDiscordB = Instance.new("TextButton")
local UICorner_34 = Instance.new("UICorner")
local Banner_2 = Instance.new("Frame")
local VegaXLogo_3 = Instance.new("ImageLabel")
local UICorner_35 = Instance.new("UICorner")
local HappyGuy_2 = Instance.new("ImageLabel")
local TitleLabel_2 = Instance.new("TextLabel")
local ScrollingBox = Instance.new("ScrollingFrame")
local TextBox_2 = Instance.new("TextBox")
local UICorner_36 = Instance.new("UICorner")
local SubTitle_7 = Instance.new("TextLabel")
local KSMenuToggleFrame = Instance.new("Frame")
local UICorner_37 = Instance.new("UICorner")
local VegaXKSToggle = Instance.new("TextButton")
local UICorner_38 = Instance.new("UICorner")
local ImageLabel_6 = Instance.new("ImageLabel")
local IntroFrame = Instance.new("Frame")
local BackgroundFrame = Instance.new("Frame")
local R1 = Instance.new("Frame")
local R2 = Instance.new("Frame")
local R3 = Instance.new("Frame")
local R4 = Instance.new("Frame")
local R5 = Instance.new("Frame")
local R6 = Instance.new("Frame")
local R7 = Instance.new("Frame")
local R8 = Instance.new("Frame")
local R9 = Instance.new("Frame")
local R10 = Instance.new("Frame")
local R11 = Instance.new("Frame")
local R12 = Instance.new("Frame")
local R13 = Instance.new("Frame")
local R14 = Instance.new("Frame")
local R15 = Instance.new("Frame")
local R16 = Instance.new("Frame")
local R17 = Instance.new("Frame")
local R18 = Instance.new("Frame")
local R19 = Instance.new("Frame")
local R20 = Instance.new("Frame")
local VegaXLogo_4 = Instance.new("ImageLabel")
local ScriptListWindow = Instance.new("Frame")
local WindowMainTitle_3 = Instance.new("TextLabel")
local CloseB_4 = Instance.new("ImageButton")
local ScriptListFrame = Instance.new("ScrollingFrame")
local S1_3 = Instance.new("Frame")
local Trash = Instance.new("ImageButton")
local UICorner_39 = Instance.new("UICorner")
local UICorner_40 = Instance.new("UICorner")
local Title_11 = Instance.new("TextLabel")
local Execute_2 = Instance.new("ImageButton")
local UICorner_41 = Instance.new("UICorner")
local UIListLayout_4 = Instance.new("UIListLayout")
local WindowSubTitle_2 = Instance.new("TextLabel")
local ExecutorWindow = Instance.new("Frame")
local ExecuteB = Instance.new("TextButton")
local UICorner_42 = Instance.new("UICorner")
local PasteandExecuteB = Instance.new("TextButton")
local UICorner_43 = Instance.new("UICorner")
local CloseB_5 = Instance.new("ImageButton")
local ScrollingBox_2 = Instance.new("ScrollingFrame")
local TextBox_3 = Instance.new("TextBox")
local Line = Instance.new("TextLabel")
local UICorner_44 = Instance.new("UICorner")
local TabbingSystem = Instance.new("Frame")
local ScriptPage = Instance.new("TextLabel")
local NextPage = Instance.new("TextButton")
local LastPage = Instance.new("TextButton")
local UICorner_45 = Instance.new("UICorner")
local EditTabName = Instance.new("ImageButton")
local EditTabBox = Instance.new("TextBox")
local WindowMainTitle_4 = Instance.new("TextLabel")
local ClearB = Instance.new("TextButton")
local UICorner_46 = Instance.new("UICorner")
local DevModeB = Instance.new("TextButton")
local UICorner_47 = Instance.new("UICorner")

--Properties:

VegaXAndroidUI.Name = "VegaXAndroidUI"
VegaXAndroidUI.Parent = gethui()

SettingsWindow.Name = "SettingsWindow"
SettingsWindow.Parent = VegaXAndroidUI
SettingsWindow.AnchorPoint = Vector2.new(0, 0.5)
SettingsWindow.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
SettingsWindow.BorderColor3 = Color3.fromRGB(30, 30, 30)
SettingsWindow.BorderSizePixel = 0
SettingsWindow.Position = UDim2.new(1, 200, 0.5, -20)
SettingsWindow.Size = UDim2.new(1, -200, 1, 40)

WindowMainTitle.Name = "WindowMainTitle"
WindowMainTitle.Parent = SettingsWindow
WindowMainTitle.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
WindowMainTitle.BackgroundTransparency = 1.000
WindowMainTitle.BorderSizePixel = 0
WindowMainTitle.Position = UDim2.new(0, 7, 0, 52)
WindowMainTitle.Size = UDim2.new(0, 200, 0, 21)
WindowMainTitle.Font = Enum.Font.GothamBold
WindowMainTitle.Text = "Settings"
WindowMainTitle.TextColor3 = Color3.fromRGB(255, 255, 255)
WindowMainTitle.TextSize = 18.000
WindowMainTitle.TextXAlignment = Enum.TextXAlignment.Left
WindowMainTitle.TextYAlignment = Enum.TextYAlignment.Top

CloseB.Name = "CloseB"
CloseB.Parent = SettingsWindow
CloseB.AnchorPoint = Vector2.new(1, 0)
CloseB.BackgroundTransparency = 1.000
CloseB.BorderSizePixel = 0
CloseB.LayoutOrder = 6
CloseB.Position = UDim2.new(1, -5, 0, 45)
CloseB.Size = UDim2.new(0, 25, 0, 25)
CloseB.ZIndex = 2
CloseB.Image = "rbxassetid://3926307971"
CloseB.ImageRectOffset = Vector2.new(884, 284)
CloseB.ImageRectSize = Vector2.new(36, 36)

ScrollingFrame.Parent = SettingsWindow
ScrollingFrame.Active = true
ScrollingFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ScrollingFrame.BackgroundTransparency = 1.000
ScrollingFrame.BorderSizePixel = 0
ScrollingFrame.Position = UDim2.new(0, 0, 0, 78)
ScrollingFrame.Size = UDim2.new(1, 0, 1, -78)
ScrollingFrame.CanvasSize = UDim2.new(0, 0, 1.5, 0)
ScrollingFrame.ScrollBarThickness = 0

UIListLayout.Parent = ScrollingFrame
UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
UIListLayout.Padding = UDim.new(0, 5)

S2.Name = "S2"
S2.Parent = ScrollingFrame
S2.BackgroundColor3 = Color3.fromRGB(38, 38, 38)
S2.BorderSizePixel = 0
S2.Size = UDim2.new(1, -10, 0, 75)

Title.Name = "Title"
Title.Parent = S2
Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Title.BackgroundTransparency = 1.000
Title.BorderSizePixel = 0
Title.Position = UDim2.new(0, 25, 0, 0)
Title.Size = UDim2.new(0.5, 0, 0.5, 0)
Title.Font = Enum.Font.GothamBold
Title.Text = "FPS Limit"
Title.TextColor3 = Color3.fromRGB(255, 255, 255)
Title.TextSize = 19.000
Title.TextXAlignment = Enum.TextXAlignment.Left
Title.TextYAlignment = Enum.TextYAlignment.Bottom

SubTitle.Name = "SubTitle"
SubTitle.Parent = S2
SubTitle.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
SubTitle.BackgroundTransparency = 1.000
SubTitle.BorderSizePixel = 0
SubTitle.Position = UDim2.new(0, 25, 0.5, 0)
SubTitle.Size = UDim2.new(0.5, 0, 0.5, 0)
SubTitle.Font = Enum.Font.Gotham
SubTitle.Text = "Set Max FPS for the Game."
SubTitle.TextColor3 = Color3.fromRGB(255, 255, 255)
SubTitle.TextSize = 14.000
SubTitle.TextXAlignment = Enum.TextXAlignment.Left
SubTitle.TextYAlignment = Enum.TextYAlignment.Top

UICorner.CornerRadius = UDim.new(0, 10)
UICorner.Parent = S2

SubmitFPS.Name = "SubmitFPS"
SubmitFPS.Parent = S2
SubmitFPS.AnchorPoint = Vector2.new(1, 0.5)
SubmitFPS.BackgroundColor3 = Color3.fromRGB(67, 67, 67)
SubmitFPS.BorderSizePixel = 0
SubmitFPS.LayoutOrder = 10
SubmitFPS.Position = UDim2.new(1, -59, 0.5, 0)
SubmitFPS.Size = UDim2.new(0, 34, 0, 34)
SubmitFPS.ZIndex = 2
SubmitFPS.Image = "rbxassetid://3926305904"
SubmitFPS.ImageRectOffset = Vector2.new(124, 924)
SubmitFPS.ImageRectSize = Vector2.new(36, 36)

UICorner_2.CornerRadius = UDim.new(0, 10)
UICorner_2.Parent = SubmitFPS

FPSTextBox.Name = "FPSTextBox"
FPSTextBox.Parent = S2
FPSTextBox.AnchorPoint = Vector2.new(1, 0.5)
FPSTextBox.BackgroundColor3 = Color3.fromRGB(89, 89, 89)
FPSTextBox.BackgroundTransparency = 0.200
FPSTextBox.BorderSizePixel = 0
FPSTextBox.Position = UDim2.new(1, -98, 0.5, 0)
FPSTextBox.Size = UDim2.new(0.200000003, 0, 0, 34)
FPSTextBox.ClearTextOnFocus = false
FPSTextBox.Font = Enum.Font.Gotham
FPSTextBox.MultiLine = true
FPSTextBox.PlaceholderText = "Max FPS"
FPSTextBox.Text = ""
FPSTextBox.TextColor3 = Color3.fromRGB(220, 220, 220)
FPSTextBox.TextSize = 16.000

UICorner_3.CornerRadius = UDim.new(0, 10)
UICorner_3.Parent = FPSTextBox

ResetFPS.Name = "ResetFPS"
ResetFPS.Parent = S2
ResetFPS.AnchorPoint = Vector2.new(1, 0.5)
ResetFPS.BackgroundColor3 = Color3.fromRGB(67, 67, 67)
ResetFPS.BorderSizePixel = 0
ResetFPS.LayoutOrder = 10
ResetFPS.Position = UDim2.new(1, -20, 0.5, 0)
ResetFPS.Size = UDim2.new(0, 34, 0, 34)
ResetFPS.ZIndex = 2
ResetFPS.Image = "rbxassetid://3926307971"
ResetFPS.ImageRectOffset = Vector2.new(404, 84)
ResetFPS.ImageRectSize = Vector2.new(36, 36)

UICorner_4.CornerRadius = UDim.new(0, 10)
UICorner_4.Parent = ResetFPS

S3.Name = "S3"
S3.Parent = ScrollingFrame
S3.BackgroundColor3 = Color3.fromRGB(38, 38, 38)
S3.BorderSizePixel = 0
S3.Size = UDim2.new(1, -10, 0, 75)

Title_2.Name = "Title"
Title_2.Parent = S3
Title_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Title_2.BackgroundTransparency = 1.000
Title_2.BorderSizePixel = 0
Title_2.Position = UDim2.new(0, 25, 0, 0)
Title_2.Size = UDim2.new(0.5, 0, 0.5, 0)
Title_2.Font = Enum.Font.GothamBold
Title_2.Text = "Dev Mode"
Title_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Title_2.TextSize = 19.000
Title_2.TextXAlignment = Enum.TextXAlignment.Left
Title_2.TextYAlignment = Enum.TextYAlignment.Bottom

SubTitle_2.Name = "SubTitle"
SubTitle_2.Parent = S3
SubTitle_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
SubTitle_2.BackgroundTransparency = 1.000
SubTitle_2.BorderSizePixel = 0
SubTitle_2.Position = UDim2.new(0, 25, 0.5, 0)
SubTitle_2.Size = UDim2.new(0.5, 0, 0.5, 0)
SubTitle_2.Font = Enum.Font.Gotham
SubTitle_2.Text = "Allow Alexis Cross Platform Connection with the Windows UI."
SubTitle_2.TextColor3 = Color3.fromRGB(255, 255, 255)
SubTitle_2.TextSize = 14.000
SubTitle_2.TextXAlignment = Enum.TextXAlignment.Left
SubTitle_2.TextYAlignment = Enum.TextYAlignment.Top

UICorner_5.CornerRadius = UDim.new(0, 10)
UICorner_5.Parent = S3

SubmitCode.Name = "SubmitCode"
SubmitCode.Parent = S3
SubmitCode.AnchorPoint = Vector2.new(1, 0.5)
SubmitCode.BackgroundColor3 = Color3.fromRGB(67, 67, 67)
SubmitCode.BorderSizePixel = 0
SubmitCode.LayoutOrder = 10
SubmitCode.Position = UDim2.new(1, -59, 0.5, 0)
SubmitCode.Size = UDim2.new(0, 34, 0, 34)
SubmitCode.ZIndex = 2
SubmitCode.Image = "rbxassetid://3926305904"
SubmitCode.ImageRectOffset = Vector2.new(124, 924)
SubmitCode.ImageRectSize = Vector2.new(36, 36)

UICorner_6.CornerRadius = UDim.new(0, 10)
UICorner_6.Parent = SubmitCode

InjectCodeTextbox.Name = "InjectCodeTextbox"
InjectCodeTextbox.Parent = S3
InjectCodeTextbox.AnchorPoint = Vector2.new(1, 0.5)
InjectCodeTextbox.BackgroundColor3 = Color3.fromRGB(89, 89, 89)
InjectCodeTextbox.BackgroundTransparency = 0.200
InjectCodeTextbox.BorderSizePixel = 0
InjectCodeTextbox.Position = UDim2.new(1, -98, 0.5, 0)
InjectCodeTextbox.Size = UDim2.new(0.200000003, 0, 0, 34)
InjectCodeTextbox.ClearTextOnFocus = false
InjectCodeTextbox.Font = Enum.Font.Gotham
InjectCodeTextbox.MultiLine = true
InjectCodeTextbox.PlaceholderText = "Inject Code"
InjectCodeTextbox.Text = ""
InjectCodeTextbox.TextColor3 = Color3.fromRGB(220, 220, 220)
InjectCodeTextbox.TextSize = 16.000

UICorner_7.CornerRadius = UDim.new(0, 10)
UICorner_7.Parent = InjectCodeTextbox

ResetCode.Name = "ResetCode"
ResetCode.Parent = S3
ResetCode.AnchorPoint = Vector2.new(1, 0.5)
ResetCode.BackgroundColor3 = Color3.fromRGB(67, 67, 67)
ResetCode.BorderSizePixel = 0
ResetCode.LayoutOrder = 10
ResetCode.Position = UDim2.new(1, -20, 0.5, 0)
ResetCode.Size = UDim2.new(0, 34, 0, 34)
ResetCode.ZIndex = 2
ResetCode.Image = "rbxassetid://3926305904"
ResetCode.ImageRectOffset = Vector2.new(644, 724)
ResetCode.ImageRectSize = Vector2.new(36, 36)

UICorner_8.CornerRadius = UDim.new(0, 10)
UICorner_8.Parent = ResetCode

S1.Name = "S1"
S1.Parent = ScrollingFrame
S1.BackgroundColor3 = Color3.fromRGB(38, 38, 38)
S1.BorderSizePixel = 0
S1.Size = UDim2.new(1, -10, 0, 75)

Title_3.Name = "Title"
Title_3.Parent = S1
Title_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Title_3.BackgroundTransparency = 1.000
Title_3.BorderSizePixel = 0
Title_3.Position = UDim2.new(0, 25, 0, 0)
Title_3.Size = UDim2.new(0.5, 0, 0.5, 0)
Title_3.Font = Enum.Font.GothamBold
Title_3.Text = "Change UI Accent Color"
Title_3.TextColor3 = Color3.fromRGB(255, 255, 255)
Title_3.TextSize = 19.000
Title_3.TextXAlignment = Enum.TextXAlignment.Left
Title_3.TextYAlignment = Enum.TextYAlignment.Bottom

SubTitle_3.Name = "SubTitle"
SubTitle_3.Parent = S1
SubTitle_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
SubTitle_3.BackgroundTransparency = 1.000
SubTitle_3.BorderSizePixel = 0
SubTitle_3.Position = UDim2.new(0, 25, 0.5, 0)
SubTitle_3.Size = UDim2.new(0.5, 0, 0.5, 0)
SubTitle_3.Font = Enum.Font.Gotham
SubTitle_3.Text = "Change Alexis  Button Colors."
SubTitle_3.TextColor3 = Color3.fromRGB(255, 255, 255)
SubTitle_3.TextSize = 14.000
SubTitle_3.TextXAlignment = Enum.TextXAlignment.Left
SubTitle_3.TextYAlignment = Enum.TextYAlignment.Top

UICorner_9.CornerRadius = UDim.new(0, 10)
UICorner_9.Parent = S1

AccentColorPreview.Name = "AccentColorPreview"
AccentColorPreview.Parent = S1
AccentColorPreview.AnchorPoint = Vector2.new(1, 0.5)
AccentColorPreview.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
AccentColorPreview.Position = UDim2.new(1, -20, 0.5, 0)
AccentColorPreview.Size = UDim2.new(0, 34, 0, 34)

UICorner_10.CornerRadius = UDim.new(0, 10)
UICorner_10.Parent = AccentColorPreview

SubmitAccent.Name = "SubmitAccent"
SubmitAccent.Parent = S1
SubmitAccent.AnchorPoint = Vector2.new(1, 0.5)
SubmitAccent.BackgroundColor3 = Color3.fromRGB(67, 67, 67)
SubmitAccent.BorderSizePixel = 0
SubmitAccent.LayoutOrder = 10
SubmitAccent.Position = UDim2.new(1, -59, 0.5, 0)
SubmitAccent.Size = UDim2.new(0, 34, 0, 34)
SubmitAccent.ZIndex = 2
SubmitAccent.Image = "rbxassetid://3926305904"
SubmitAccent.ImageRectOffset = Vector2.new(124, 924)
SubmitAccent.ImageRectSize = Vector2.new(36, 36)

UICorner_11.CornerRadius = UDim.new(0, 10)
UICorner_11.Parent = SubmitAccent

AccentTextBox.Name = "AccentTextBox"
AccentTextBox.Parent = S1
AccentTextBox.AnchorPoint = Vector2.new(1, 0.5)
AccentTextBox.BackgroundColor3 = Color3.fromRGB(89, 89, 89)
AccentTextBox.BackgroundTransparency = 0.200
AccentTextBox.BorderSizePixel = 0
AccentTextBox.Position = UDim2.new(1, -98, 0.5, 0)
AccentTextBox.Size = UDim2.new(0.200000003, 0, 0, 34)
AccentTextBox.ClearTextOnFocus = false
AccentTextBox.Font = Enum.Font.Gotham
AccentTextBox.MultiLine = true
AccentTextBox.PlaceholderText = "Hex Value"
AccentTextBox.Text = ""
AccentTextBox.TextColor3 = Color3.fromRGB(220, 220, 220)
AccentTextBox.TextSize = 16.000

UICorner_12.CornerRadius = UDim.new(0, 10)
UICorner_12.Parent = AccentTextBox

S4.Name = "S4"
S4.Parent = ScrollingFrame
S4.BackgroundColor3 = Color3.fromRGB(38, 38, 38)
S4.BorderSizePixel = 0
S4.Size = UDim2.new(1, -10, 0, 75)
S4.Visible = false

Title_4.Name = "Title"
Title_4.Parent = S4
Title_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Title_4.BackgroundTransparency = 1.000
Title_4.BorderSizePixel = 0
Title_4.Position = UDim2.new(0, 25, 0, 0)
Title_4.Size 
